version: 2

jobs:
  deploy-docs:
    docker:
      - image: circleci/python:3.7.3-stretch
    working_directory: /tmp/docs-deployment
    steps:
      - checkout
      - run:
          name: Build docs page
          command: |
            curl -sL https://deb.nodesource.com/setup_11.x | sudo bash -
            sudo apt-get install -y nodejs
            cd website
            npm install
            npm run build
      - run:
          name: Deploy to S3
          command: |
            virtualenv ~/sdk
            source ~/sdk/bin/activate
            pip install awscli --upgrade
            mv $WEBSITE_BUILD_DIR/index.html $WEBSITE_BUILD_DIR/redirect.html 
            aws s3 sync $WEBSITE_BUILD_DIR $AWS_S3_BUCKET --acl public-read
            aws s3 mv "$AWS_S3_BUCKET/redirect.html $AWS_S3_BUCKET/index.html --acl public-read --metadata "Website-Redirect-Location=/docs/"

workflows:
  version: 2
  docs-deployment:
    jobs:
      - deploy-docs:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/