version: 2

jobs:
  deploy-docs:
    docker:
      - image: circleci/python:3.7.3-stretch
    working_directory: /tmp/docs-deployment
    steps:
      - checkout
      - run:
          name: Build docs page
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
            sudo apt-get install -y nodejs
            cd website
            npm install
            npm run build
      - run:
          name: Deploy to S3
          command: |
            virtualenv ~/sdk
            source ~/sdk/bin/activate
            pip install awscli --upgrade
            rm website/build/index.html
            aws s3 sync website/build $AWS_S3_BUCKET --cache-control "public,max-age=86400,s-maxage=86400" --delete
            aws cloudfront create-invalidation --distribution-id $AWS_CF_DISTRIBUTION --paths "/*"

workflows:
  version: 2
  docs-deployment:
    jobs:
      - deploy-docs:
          filters:
            branches:
              only: master
