name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1.4.4

    - uses: bahmutov/npm-install@v1
      with:
        working-directory: website

    - run: npm run build
      working-directory: website

    - name: Push to S3
      run: |
        aws s3 sync website/build s3://${{ secrets.AWS_S3_BUCKET }} --cache-control "public,max-age=86400,s-maxage=86400" --delete
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_DISTRIBUTION }} --paths "/*"
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
